//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB07.MF1755.KVHAI.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB07.MF1755.KVHAI.Domain.Resource.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại chỉ không được vượt quá 255 ký tự.
        /// </summary>
        public static string Error_AddressMaxLength {
            get {
                return ResourceManager.GetString("Error_AddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn không được để trống.
        /// </summary>
        public static string Error_ApplyDateOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_ApplyDateOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người duyệt không được để trống.
        /// </summary>
        public static string Error_ApprovalOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_ApprovalOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh không được vượt quá 255 ký tự.
        /// </summary>
        public static string Error_BankBranchMaxLength {
            get {
                return ResourceManager.GetString("Error_BankBranchMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng không được vượt quá 255 ký tự.
        /// </summary>
        public static string Error_BankNameMaxLength {
            get {
                return ResourceManager.GetString("Error_BankNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng không được vượt quá 25 ký tự.
        /// </summary>
        public static string Error_BankNumberMaxLength {
            get {
                return ResourceManager.GetString("Error_BankNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ giữa ca từ phải lớn hơn hoặc bằng Làm thêm từ.
        /// </summary>
        public static string Error_BreakTimeFromLessFromDateOvertime {
            get {
                return ResourceManager.GetString("Error_BreakTimeFromLessFromDateOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ giữa ca từ không được để trống khi đã nhập Nghỉ giữa ca đến.
        /// </summary>
        public static string Error_BreakTimeFromOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_BreakTimeFromOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm thêm đến phải lớn hơn hoặc bằng Nghỉ giữa ca đến.
        /// </summary>
        public static string Error_BreakTimeToBiggerToDateOvertime {
            get {
                return ResourceManager.GetString("Error_BreakTimeToBiggerToDateOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ giữa ca đến phải lớn hơn hoặc bằng Nghỉ giữa ca từ.
        /// </summary>
        public static string Error_BreakTimeToLessBreakTimeFromOvertime {
            get {
                return ResourceManager.GetString("Error_BreakTimeToLessBreakTimeFromOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ giữa ca đến không được để trống khi đã nhập Nghỉ giữa ca từ.
        /// </summary>
        public static string Error_BreakTimeToOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_BreakTimeToOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh không được vượt quá 255 ký tự.
        /// </summary>
        public static string Error_CareerTitlesMaxLength {
            get {
                return ResourceManager.GetString("Error_CareerTitlesMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu định dạng không hợp lệ.
        /// </summary>
        public static string Error_DateFormatInvalid {
            get {
                return ResourceManager.GetString("Error_DateFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Error_DateOfBirthInvalid {
            get {
                return ResourceManager.GetString("Error_DateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị ko hợp lệ.
        /// </summary>
        public static string Error_DepartmentInvalid {
            get {
                return ResourceManager.GetString("Error_DepartmentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không tồn tại.
        /// </summary>
        public static string Error_DepartmentNotFound {
            get {
                return ResourceManager.GetString("Error_DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được để trống.
        /// </summary>
        public static string Error_DepartmentRequired {
            get {
                return ResourceManager.GetString("Error_DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string Error_EmailInvalid {
            get {
                return ResourceManager.GetString("Error_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp không được vượt quá 50 ký tự.
        /// </summary>
        public static string Error_EmailMaxLength {
            get {
                return ResourceManager.GetString("Error_EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống vui lòng kiểm tra lại.
        /// </summary>
        public static string Error_EmployeeCodeExists {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không vượt quá 20 ký tự.
        /// </summary>
        public static string Error_EmployeeCodeInvalid {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được vượt quá 20 ký tự.
        /// </summary>
        public static string Error_EmployeeCodeMaxLength {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống.
        /// </summary>
        public static string Error_EmployeeCodeRequired {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên không tồn tại trong hệ thống.
        /// </summary>
        public static string Error_EmployeeNotFound {
            get {
                return ResourceManager.GetString("Error_EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nộp đơn không được để trống.
        /// </summary>
        public static string Error_EmployeeOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_EmployeeOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường lọc không hợp lệ.
        /// </summary>
        public static string Error_FieldFilterInvalid {
            get {
                return ResourceManager.GetString("Error_FieldFilterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm thêm từ không được lớn hơn làm thêm đến.
        /// </summary>
        public static string Error_FromDateBiggerTodateOvertime {
            get {
                return ResourceManager.GetString("Error_FromDateBiggerTodateOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm thêm từ không được để trống.
        /// </summary>
        public static string Error_FromDateOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_FromDateOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được vượt quá 100 ký tự.
        /// </summary>
        public static string Error_FullNameMaxLength {
            get {
                return ResourceManager.GetString("Error_FullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được để trống.
        /// </summary>
        public static string Error_FullNameRequired {
            get {
                return ResourceManager.GetString("Error_FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Error_IdentityDateInvalid {
            get {
                return ResourceManager.GetString("Error_IdentityDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CCCD không được vượt quá 25 ký tự.
        /// </summary>
        public static string Error_IdentityNumberMaxLength {
            get {
                return ResourceManager.GetString("Error_IdentityNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp không được vượt quá 255 ký tự.
        /// </summary>
        public static string Error_IdentityPlaceMaxLength {
            get {
                return ResourceManager.GetString("Error_IdentityPlaceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập từ người dùng.
        /// </summary>
        public static string Error_Input {
            get {
                return ResourceManager.GetString("Error_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại cố định không được vượt quá 50 ký tự.
        /// </summary>
        public static string Error_LandlinePhoneMaxLength {
            get {
                return ResourceManager.GetString("Error_LandlinePhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có độ dài tối thiểu là {1}..
        /// </summary>
        public static string Error_MinArrayLength {
            get {
                return ResourceManager.GetString("Error_MinArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên làm thêm không được để trống.
        /// </summary>
        public static string Error_OvertimeEmployeesRequired {
            get {
                return ResourceManager.GetString("Error_OvertimeEmployeesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm làm thêm không được để trống.
        /// </summary>
        public static string Error_OverTimeInWorkingShiftOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_OverTimeInWorkingShiftOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại làm thêm không được để trống.
        /// </summary>
        public static string Error_OvertimeTypeRequired {
            get {
                return ResourceManager.GetString("Error_OvertimeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại đi động không được vượt quá 50 ký tự.
        /// </summary>
        public static string Error_PhoneNumberMaxLength {
            get {
                return ResourceManager.GetString("Error_PhoneNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do làm thêm không được để trống.
        /// </summary>
        public static string Error_ReasonOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_ReasonOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái không được để trống.
        /// </summary>
        public static string Error_StatusOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_StatusOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm thêm đến phải lớn hơn hoặc bằng Nghỉ giữa ca đến.
        /// </summary>
        public static string Error_ToDateLessBreakTimeToOvertime {
            get {
                return ResourceManager.GetString("Error_ToDateLessBreakTimeToOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm thêm đến không được để trống.
        /// </summary>
        public static string Error_ToDateOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_ToDateOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca áp dụng không được để trống.
        /// </summary>
        public static string Error_WorkingShiftOvertimeRequired {
            get {
                return ResourceManager.GetString("Error_WorkingShiftOvertimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string NumericalOrder {
            get {
                return ResourceManager.GetString("NumericalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên làm thêm.
        /// </summary>
        public static string OvertimeEmployees {
            get {
                return ResourceManager.GetString("OvertimeEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký làm thêm.
        /// </summary>
        public static string Overtimes {
            get {
                return ResourceManager.GetString("Overtimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt.
        /// </summary>
        public static string Status_Approved {
            get {
                return ResourceManager.GetString("Status_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string Status_Refuse {
            get {
                return ResourceManager.GetString("Status_Refuse", resourceCulture);
            }
        }
    }
}
